static const char x86optab[512] =
"HHHHAD@@HHHHAD@@HHHHAD@@HHHHAD@@HHHHADP@HHHHADP@HHHHADP@HHHHADP@"
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@hHPPPPDLAI@@@@AAAAAAAAAAAAAAAA"
"ILIIHHHHHHHHHHHh@@@@@@@@@@F@@@@@EEEE@@@@AD@@@@@@AAAAAAAADDDDDDDD"
"IIB@hhILC@B@@A@@HHHHAA@@HHHHHHHHAAAAAAAADDFA@@@@P@PP@@il@@@@@@HH"
"HHHHp@@@@@p@pHppHHHHHHHHHpHHpppHHHHHppppHHHHHHHH@@@@@@p@PpPppppp"
"HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHIIIHHH@HHppHHHH"
"DDDDDDDDDDDDDDDDHHHHHHHHHHHHHHHH@@@HIHpp@@@HIHHHHHHHHHHHHHIHHHHH"
"HHIHIIIH@@@@@@@@HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH@";
