static const char x86optab[512] =
"HHHHAD@@HHHHAD@@HHHHAD@@HHHHAD@@HHHHADP@HHHHADP@HHHHADP@HHHHADP@"
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@HHPPPPDLAI@@@@AAAAAAAAAAAAAAAA"
"ILIIHHHHHHHHHHHH@@@@@@@@@@F@@@@@EEEE@@@@AD@@@@@@AAAAAAAADDDDDDDD"
"IIB@HHILC@B@@A@@HHHHAA@@HHHHHHHHAAAAAAAADDFA@@@@P@PP@@IL@@@@@@HH"
"HHHH`@@@@@`@`H``HHHHHHHHH`HH```HHHHH````HHHHHHHH@@@@@@`@P`P`````"
"HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHIIIHHH@HH``HHHH"
"DDDDDDDDDDDDDDDDHHHHHHHHHHHHHHHH@@@HIH``@@@HIHHHHHHHHHHHHHIHHHHH"
"HHIHIIIH@@@@@@@@HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH@";
