static const char x86optab[512] =
"HHHHAD@@HHHHAD@PHHHHAD@@HHHHAD@@HHHHADP@HHHHADP@HHHHADP@HHHHADP@"
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@HHPPPPDLAI@@@@AAAAAAAAAAAAAAAA"
"ILIIHHHHHHHHHHHH@@@@@@@@@@F@@@@@EEEE@@@@AD@@@@@@AAAAAAAADDDDDDDD"
"IIB@HHILC@B@@A@@HHHHAA@@HHHHHHHHAAAAAAAADDFA@@@@P@PP@@il@@@@@@HH"
"HHHHp@@@@@p@pHppHHHHHHHHHpHHpppHHHHHppppHHHHHHHH@@@@@@p@PpPppppp"
"HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHIIIHHH@HHppHHHH"
"DDDDDDDDDDDDDDDDHHHHHHHHHHHHHHHH@@@HIHpp@@@HIHHHHHHHHHHHHHIHHHHH"
"HHIHIIIH@@@@@@@@HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH@";
